/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookingId from './BookingId';
import RoomDTO from './RoomDTO';

/**
 * The BookingForm model module.
 * @module model/BookingForm
 * @version v0
 */
class BookingForm {
    /**
     * Constructs a new <code>BookingForm</code>.
     * @alias module:model/BookingForm
     */
    constructor() { 
        
        BookingForm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingForm} obj Optional instance to populate.
     * @return {module:model/BookingForm} The populated <code>BookingForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingForm();

            if (data.hasOwnProperty('singleRoomCount')) {
                obj['singleRoomCount'] = ApiClient.convertToType(data['singleRoomCount'], 'Number');
            }
            if (data.hasOwnProperty('doubleRoomCount')) {
                obj['doubleRoomCount'] = ApiClient.convertToType(data['doubleRoomCount'], 'Number');
            }
            if (data.hasOwnProperty('superiorRoomCount')) {
                obj['superiorRoomCount'] = ApiClient.convertToType(data['superiorRoomCount'], 'Number');
            }
            if (data.hasOwnProperty('checkInDate')) {
                obj['checkInDate'] = ApiClient.convertToType(data['checkInDate'], 'String');
            }
            if (data.hasOwnProperty('checkOutDate')) {
                obj['checkOutDate'] = ApiClient.convertToType(data['checkOutDate'], 'String');
            }
            if (data.hasOwnProperty('voucherCode')) {
                obj['voucherCode'] = ApiClient.convertToType(data['voucherCode'], 'String');
            }
            if (data.hasOwnProperty('bookingId')) {
                obj['bookingId'] = BookingId.constructFromObject(data['bookingId']);
            }
            if (data.hasOwnProperty('roomList')) {
                obj['roomList'] = ApiClient.convertToType(data['roomList'], [RoomDTO]);
            }
            if (data.hasOwnProperty('validDuration')) {
                obj['validDuration'] = ApiClient.convertToType(data['validDuration'], 'Boolean');
            }
            if (data.hasOwnProperty('validCategoryCount')) {
                obj['validCategoryCount'] = ApiClient.convertToType(data['validCategoryCount'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} singleRoomCount
 */
BookingForm.prototype['singleRoomCount'] = undefined;

/**
 * @member {Number} doubleRoomCount
 */
BookingForm.prototype['doubleRoomCount'] = undefined;

/**
 * @member {Number} superiorRoomCount
 */
BookingForm.prototype['superiorRoomCount'] = undefined;

/**
 * @member {String} checkInDate
 */
BookingForm.prototype['checkInDate'] = undefined;

/**
 * @member {String} checkOutDate
 */
BookingForm.prototype['checkOutDate'] = undefined;

/**
 * @member {String} voucherCode
 */
BookingForm.prototype['voucherCode'] = undefined;

/**
 * @member {module:model/BookingId} bookingId
 */
BookingForm.prototype['bookingId'] = undefined;

/**
 * @member {Array.<module:model/RoomDTO>} roomList
 */
BookingForm.prototype['roomList'] = undefined;

/**
 * @member {Boolean} validDuration
 */
BookingForm.prototype['validDuration'] = undefined;

/**
 * @member {Boolean} validCategoryCount
 */
BookingForm.prototype['validCategoryCount'] = undefined;






export default BookingForm;

