/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GuestId from './GuestId';

/**
 * The GuestDTO model module.
 * @module model/GuestDTO
 * @version v0
 */
class GuestDTO {
    /**
     * Constructs a new <code>GuestDTO</code>.
     * @alias module:model/GuestDTO
     */
    constructor() { 
        
        GuestDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GuestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GuestDTO} obj Optional instance to populate.
     * @return {module:model/GuestDTO} The populated <code>GuestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GuestDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('guestId')) {
                obj['guestId'] = GuestId.constructFromObject(data['guestId']);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('streetAddress')) {
                obj['streetAddress'] = ApiClient.convertToType(data['streetAddress'], 'String');
            }
            if (data.hasOwnProperty('zip')) {
                obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('guestType')) {
                obj['guestType'] = ApiClient.convertToType(data['guestType'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('agencyName')) {
                obj['agencyName'] = ApiClient.convertToType(data['agencyName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GuestDTO.prototype['id'] = undefined;

/**
 * @member {module:model/GuestId} guestId
 */
GuestDTO.prototype['guestId'] = undefined;

/**
 * @member {String} firstName
 */
GuestDTO.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
GuestDTO.prototype['lastName'] = undefined;

/**
 * @member {String} streetAddress
 */
GuestDTO.prototype['streetAddress'] = undefined;

/**
 * @member {String} zip
 */
GuestDTO.prototype['zip'] = undefined;

/**
 * @member {String} city
 */
GuestDTO.prototype['city'] = undefined;

/**
 * @member {String} country
 */
GuestDTO.prototype['country'] = undefined;

/**
 * @member {String} phoneNumber
 */
GuestDTO.prototype['phoneNumber'] = undefined;

/**
 * @member {String} email
 */
GuestDTO.prototype['email'] = undefined;

/**
 * @member {module:model/GuestDTO.GuestTypeEnum} guestType
 */
GuestDTO.prototype['guestType'] = undefined;

/**
 * @member {String} companyName
 */
GuestDTO.prototype['companyName'] = undefined;

/**
 * @member {String} agencyName
 */
GuestDTO.prototype['agencyName'] = undefined;





/**
 * Allowed values for the <code>guestType</code> property.
 * @enum {String}
 * @readonly
 */
GuestDTO['GuestTypeEnum'] = {

    /**
     * value: "COMPANY"
     * @const
     */
    "COMPANY": "COMPANY",

    /**
     * value: "TRAVEL_AGENCY"
     * @const
     */
    "TRAVEL_AGENCY": "TRAVEL_AGENCY",

    /**
     * value: "REGULAR"
     * @const
     */
    "REGULAR": "REGULAR"
};



export default GuestDTO;

