/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.BookingForm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookingForm', function() {
    it('should create an instance of BookingForm', function() {
      // uncomment below and update the code to test BookingForm
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be.a(OpenApiDefinition.BookingForm);
    });

    it('should have the property singleRoomCount (base name: "singleRoomCount")', function() {
      // uncomment below and update the code to test the property singleRoomCount
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property doubleRoomCount (base name: "doubleRoomCount")', function() {
      // uncomment below and update the code to test the property doubleRoomCount
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property superiorRoomCount (base name: "superiorRoomCount")', function() {
      // uncomment below and update the code to test the property superiorRoomCount
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property checkInDate (base name: "checkInDate")', function() {
      // uncomment below and update the code to test the property checkInDate
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property checkOutDate (base name: "checkOutDate")', function() {
      // uncomment below and update the code to test the property checkOutDate
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property voucherCode (base name: "voucherCode")', function() {
      // uncomment below and update the code to test the property voucherCode
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property bookingId (base name: "bookingId")', function() {
      // uncomment below and update the code to test the property bookingId
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property roomList (base name: "roomList")', function() {
      // uncomment below and update the code to test the property roomList
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property validDuration (base name: "validDuration")', function() {
      // uncomment below and update the code to test the property validDuration
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

    it('should have the property validCategoryCount (base name: "validCategoryCount")', function() {
      // uncomment below and update the code to test the property validCategoryCount
      //var instance = new OpenApiDefinition.BookingForm();
      //expect(instance).to.be();
    });

  });

}));
